version: "3"
services:
  server:
    image: fsappka
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/fs-library?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=databaze123
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=databaze123
      - MYSQL_DATABASE=fs-library
    volumes:
      - "./databazesql.sql:/docker-entrypoint-initdb.d/1.sql"
      
  adminer:
    image: adminer:latest
    networks:
      - springmysql-net
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 7777:8080
networks:
  springmysql-net: