version: "3"
services:
  server:
    image: eclipse-temurin:17.0.5_8-jre
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/fs-library?useSSL=false&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=databaze123
      - MYSQL_DATABASE=fs-library
      - MYSQL_USER=springstudent
      - MYSQL_PASSWORD=springstudent

networks:
  springmysql-net: