version: "3"
services:
  server:
    image: fsappka
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/fs-library?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true

  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=databaze123
      - MYSQL_DATABASE=fs-library
    ports:
      - 3307:3306
    volumes:
      - "./databazesql.sql:/docker-entrypoint-initdb.d/1.sql"
  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysqldb
    ports:
      - 7777:8080